export const initialProducts = [
  {
    id: "1",
    sku: "SKU-1001",
    name: "Apple iPhone 15 Pro 128 GB",
    category: "Elektronik",
    stock: 45,
    reserved: 12,
    threshold: 20,
    location: "A-01",
    velocity: "Hızlı",
    price: 64999,
    wholesalePrice: 62150,
    minOrderQty: 1,
    supplier: "Apple Distribütör",
    channel: "Pazaryeri + Bayi",
    image: "https://images.unsplash.com/photo-1696446701796-da61225697cc?w=500&q=80",
    description: "Titanyum tasarım, A17 Pro çip ve güçlü kamera sistemi.",
    brand: "Apple",
    rating: 4.8,
  },
  {
    id: "2",
    sku: "SKU-1002",
    name: "Samsung Galaxy S24 Ultra 256 GB",
    category: "Elektronik",
    stock: 30,
    reserved: 5,
    threshold: 15,
    location: "A-02",
    velocity: "Hızlı",
    price: 69999,
    wholesalePrice: 66200,
    minOrderQty: 1,
    supplier: "Samsung Türkiye",
    channel: "Pazaryeri + Bayi",
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500&q=80",
    description: "Galaxy AI destekli, üst segment amiral gemisi deneyimi.",
    brand: "Samsung",
    rating: 4.7,
  },
  {
    id: "3",
    sku: "SKU-1003",
    name: "Sony WH-1000XM5 Kablosuz Kulaklık",
    category: "Elektronik",
    stock: 84,
    reserved: 18,
    threshold: 35,
    location: "A-12",
    velocity: "Hızlı",
    price: 12999,
    wholesalePrice: 11890,
    minOrderQty: 2,
    supplier: "Sony Eurasia",
    channel: "B2B + Web",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500&q=80",
    description: "Yüksek segment gürültü engelleme ve premium ses deneyimi.",
    brand: "Sony",
    rating: 4.9,
  },
  {
    id: "4",
    sku: "SKU-1004",
    name: "MacBook Air M3 13.6 inç",
    category: "Elektronik",
    stock: 15,
    reserved: 2,
    threshold: 10,
    location: "A-05",
    velocity: "Normal",
    price: 42999,
    wholesalePrice: 40600,
    minOrderQty: 1,
    supplier: "Apple Distribütör",
    channel: "Web + Bayi",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&q=80",
    description: "Yeni nesil M3 işlemci ile hafif, hızlı ve verimli dizüstü.",
    brand: "Apple",
    rating: 4.9,
  },
  {
    id: "5",
    sku: "SKU-1005",
    name: "Dyson V15 Detect Absolute",
    category: "Elektronik",
    stock: 8,
    reserved: 3,
    threshold: 10,
    location: "A-15",
    velocity: "Hızlı",
    price: 28999,
    wholesalePrice: 27150,
    minOrderQty: 1,
    supplier: "Dyson Türkiye",
    channel: "Pazaryeri",
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500&q=80",
    description: "Lazer destekli toz algılama ile güçlü temizlik deneyimi.",
    brand: "Dyson",
    rating: 4.8,
  },
  {
    id: "6",
    sku: "SKU-1006",
    name: "LG 55 İnç 4K Smart OLED TV",
    category: "Elektronik",
    stock: 12,
    reserved: 1,
    threshold: 5,
    location: "B-01",
    velocity: "Yavaş",
    price: 45999,
    wholesalePrice: 43800,
    minOrderQty: 1,
    supplier: "LG Türkiye",
    channel: "Web + Mağaza",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&q=80",
    description: "OLED panel ile güçlü kontrast ve sinematik görüntü kalitesi.",
    brand: "LG",
    rating: 4.7,
  },
  {
    id: "7",
    sku: "SKU-2001",
    name: "Oversize Organik Pamuk Tişört",
    category: "Moda",
    stock: 120,
    reserved: 25,
    threshold: 50,
    location: "C-01",
    velocity: "Hızlı",
    price: 349,
    wholesalePrice: 255,
    minOrderQty: 6,
    supplier: "Mavi Tedarik",
    channel: "Bayi + Web",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80",
    description: "Rahat kesimli ve günlük kullanım için ideal premium basic ürün.",
    brand: "Mavi",
    rating: 4.5,
  },
  {
    id: "8",
    sku: "SKU-2002",
    name: "Yüksek Bel Skinny Jean",
    category: "Moda",
    stock: 85,
    reserved: 10,
    threshold: 30,
    location: "C-05",
    velocity: "Orta",
    price: 599,
    wholesalePrice: 448,
    minOrderQty: 4,
    supplier: "Levi's Distribütör",
    channel: "Web + Bayi",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&q=80",
    description: "Esnek kumaş yapısı ile gün boyu konfor sağlayan jean.",
    brand: "Levi's",
    rating: 4.6,
  },
  {
    id: "9",
    sku: "SKU-2003",
    name: "Erkek Spor Ayakkabı Air Max",
    category: "Moda",
    stock: 45,
    reserved: 8,
    threshold: 20,
    location: "D-12",
    velocity: "Hızlı",
    price: 3299,
    wholesalePrice: 2840,
    minOrderQty: 2,
    supplier: "Nike Türkiye",
    channel: "Pazaryeri + Bayi",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80",
    description: "Konfor odaklı taban yapısı ile günlük ve sportif kullanım için.",
    brand: "Nike",
    rating: 4.8,
  },
  {
    id: "10",
    sku: "SKU-2004",
    name: "Deri Çapraz Askılı Çanta",
    category: "Moda",
    stock: 32,
    reserved: 4,
    threshold: 15,
    location: "C-11",
    velocity: "Normal",
    price: 1199,
    wholesalePrice: 920,
    minOrderQty: 2,
    supplier: "Vakko",
    channel: "Web + Bayi",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&q=80",
    description: "Şık görünüm ve günlük kullanım için dengeli ölçülerde tasarım.",
    brand: "Vakko",
    rating: 4.7,
  },
  {
    id: "11",
    sku: "SKU-2005",
    name: "Kapüşonlu Sweatshirt",
    category: "Moda",
    stock: 150,
    reserved: 40,
    threshold: 60,
    location: "C-02",
    velocity: "Hızlı",
    price: 499,
    wholesalePrice: 372,
    minOrderQty: 5,
    supplier: "Puma",
    channel: "B2B + Web",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&q=80",
    description: "Kalın kumaşıyla sezonluk satışlarda öne çıkan rahat sweatshirt.",
    brand: "Puma",
    rating: 4.4,
  },
  {
    id: "12",
    sku: "SKU-2006",
    name: "Güneş Gözlüğü UV400",
    category: "Moda",
    stock: 65,
    reserved: 5,
    threshold: 20,
    location: "C-20",
    velocity: "Normal",
    price: 1899,
    wholesalePrice: 1490,
    minOrderQty: 3,
    supplier: "Ray-Ban",
    channel: "Pazaryeri",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&q=80",
    description: "Polarize cam ve premium çerçeve ile yüksek algılı aksesuar.",
    brand: "Ray-Ban",
    rating: 4.8,
  },
];

export const initialOrders = [
  {
    id: "ORD-9124",
    customer: "Trendyol Mağazası",
    dealer: "İzmir Alt Bayi",
    items: 18,
    total: 182450,
    priority: "Yüksek",
    channel: "Pazaryeri",
    orderType: "Bayi Siparişi",
    approvalStatus: "Onay Bekliyor",
    paymentStatus: "Ödeme Bekliyor",
    fulfillmentStatus: "Onay Bekliyor",
    shipmentStatus: "Sevk Bekliyor",
    status: "Yeni Sipariş",
  },
  {
    id: "ORD-9125",
    customer: "Hepsiburada",
    dealer: "Merkez Operasyon",
    items: 7,
    total: 42390,
    priority: "Normal",
    channel: "Pazaryeri",
    orderType: "Perakende Sipariş",
    approvalStatus: "Onaylandı",
    paymentStatus: "Ödeme Alındı",
    fulfillmentStatus: "Hazırlanıyor",
    shipmentStatus: "Sevk Bekliyor",
    status: "Depoda Hazırlanıyor",
  },
  {
    id: "ORD-9126",
    customer: "Shopify Mağaza",
    dealer: "Ankara Bayi",
    items: 31,
    total: 128320,
    priority: "Yüksek",
    channel: "B2B",
    orderType: "Bayi Siparişi",
    approvalStatus: "Onaylandı",
    paymentStatus: "Ödeme Alındı",
    fulfillmentStatus: "Paketlendi",
    shipmentStatus: "Kargoya Verildi",
    status: "Sevk Edildi",
  },
  {
    id: "ORD-9127",
    customer: "Amazon TR",
    dealer: "Merkez Depo",
    items: 11,
    total: 61280,
    priority: "Normal",
    channel: "Pazaryeri",
    orderType: "Perakende Sipariş",
    approvalStatus: "Onaylandı",
    paymentStatus: "Ödeme Alındı",
    fulfillmentStatus: "Paketlendi",
    shipmentStatus: "Teslim Edildi",
    status: "Tamamlandı",
  },
];

export const initialActivity = [
  "12 ürün kritik stok listesine eklendi",
  "42 sipariş için kargo etiketi üretildi",
  "A-12 rafında sayım farkı kapatıldı",
  "Yeni bayi fiyat listesi yayınlandı",
];
